language: objective-c
before_install:
    - brew update
    - brew install xctool
    - ls -la
script: xctool -workspace 'LLBinaryOperators.xcworkspace' -scheme 'LLBinaryOperators' -configuration Debug -sdk iphonesimulator clean build test
