language: objective-c
before_install:
    - brew update
    - brew install xctool --HEAD
    - ls -la
script: xctool -workspace LLBinaryOperators.xcworkspace -sdk iphonesimulator -scheme LLBinaryOperators clean build test
